-- 50_history.sql — SCD2 history tables (generated by schemagen)
CREATE TABLE loan.borrower_history (
  history_id    BIGSERIAL PRIMARY KEY,
  borrower_id        BIGINT NOT NULL REFERENCES loan.borrower(borrower_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.party_address_history (
  history_id    BIGSERIAL PRIMARY KEY,
  address_id        BIGINT NOT NULL REFERENCES loan.party_address(address_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.loan_application_history (
  history_id    BIGSERIAL PRIMARY KEY,
  application_id        BIGINT NOT NULL REFERENCES loan.loan_application(application_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.vehicle_history (
  history_id    BIGSERIAL PRIMARY KEY,
  vehicle_id        BIGINT NOT NULL REFERENCES loan.vehicle(vehicle_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.loan_terms_history (
  history_id    BIGSERIAL PRIMARY KEY,
  loan_terms_id        BIGINT NOT NULL REFERENCES loan.loan_terms(loan_terms_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.rate_tier_history (
  history_id    BIGSERIAL PRIMARY KEY,
  rate_tier_id        BIGINT NOT NULL REFERENCES loan.rate_tier(rate_tier_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.underwriting_decision_history (
  history_id    BIGSERIAL PRIMARY KEY,
  decision_id        BIGINT NOT NULL REFERENCES loan.underwriting_decision(decision_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.policy_rule_history (
  history_id    BIGSERIAL PRIMARY KEY,
  policy_rule_id        BIGINT NOT NULL REFERENCES loan.policy_rule(policy_rule_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.income_source_history (
  history_id    BIGSERIAL PRIMARY KEY,
  income_source_id        BIGINT NOT NULL REFERENCES loan.income_source(income_source_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.employment_record_history (
  history_id    BIGSERIAL PRIMARY KEY,
  employment_id        BIGINT NOT NULL REFERENCES loan.employment_record(employment_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.loan_history (
  history_id    BIGSERIAL PRIMARY KEY,
  loan_id        BIGINT NOT NULL REFERENCES loan.loan(loan_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
CREATE TABLE loan.collateral_valuation_history (
  history_id    BIGSERIAL PRIMARY KEY,
  valuation_id        BIGINT NOT NULL REFERENCES loan.collateral_valuation(valuation_id),
  valid_from    TIMESTAMPTZ NOT NULL DEFAULT now(),
  valid_to      TIMESTAMPTZ,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  changed_by    TEXT,
  change_reason TEXT,
  snapshot      JSONB
);
