-- 60_xref.sql — many-to-many bridge tables (generated by schemagen)
CREATE TABLE loan.decision_reason_xref (
  decision_id BIGINT REFERENCES loan.underwriting_decision(decision_id),
  reason_code TEXT REFERENCES ref.decision_reason(code),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (decision_id, reason_code)
);
CREATE TABLE loan.application_stipulation_xref (
  application_id BIGINT REFERENCES loan.loan_application(application_id),
  stipulation_id BIGINT REFERENCES loan.stipulation(stipulation_id),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (application_id, stipulation_id)
);
CREATE TABLE loan.policy_rule_region_xref (
  policy_rule_id BIGINT REFERENCES loan.policy_rule(policy_rule_id),
  region_id INT REFERENCES ref.region(region_id),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (policy_rule_id, region_id)
);
CREATE TABLE loan.borrower_document_xref (
  borrower_id BIGINT REFERENCES loan.borrower(borrower_id),
  document_id BIGINT REFERENCES doc.document(document_id),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (borrower_id, document_id)
);
CREATE TABLE loan.application_document_xref (
  application_id BIGINT REFERENCES loan.loan_application(application_id),
  document_id BIGINT REFERENCES doc.document(document_id),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (application_id, document_id)
);
CREATE TABLE loan.loan_fee_xref (
  loan_id BIGINT REFERENCES loan.loan(loan_id),
  fee_code TEXT REFERENCES ref.fee_type(code),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (loan_id, fee_code)
);
CREATE TABLE loan.rate_sheet_region_xref (
  rate_sheet_id BIGINT REFERENCES loan.rate_sheet(rate_sheet_id),
  region_id INT REFERENCES ref.region(region_id),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (rate_sheet_id, region_id)
);
CREATE TABLE loan.underwriter_product_xref (
  underwriter_id BIGINT REFERENCES loan.underwriter(underwriter_id),
  product_code TEXT REFERENCES ref.loan_product(code),
  weight NUMERIC(6,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (underwriter_id, product_code)
);
