-- 70_servicing.sql — servicing-detail tables (generated by schemagen)
CREATE TABLE loan.amortization_schedule (
  amortization_schedule_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), period INT, due_date DATE, principal NUMERIC(12,2), interest NUMERIC(12,2), balance NUMERIC(14,2)
);
CREATE TABLE loan.payment_allocation (
  payment_allocation_id BIGSERIAL PRIMARY KEY,
  payment_id BIGINT REFERENCES loan.payment(payment_id), to_principal NUMERIC(12,2), to_interest NUMERIC(12,2), to_fees NUMERIC(12,2)
);
CREATE TABLE loan.escrow (
  escrow_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), balance NUMERIC(12,2), monthly_amount NUMERIC(12,2), as_of_date DATE
);
CREATE TABLE loan.late_fee (
  late_fee_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), assessed_date DATE, amount NUMERIC(10,2), waived BOOLEAN DEFAULT false
);
CREATE TABLE loan.payoff (
  payoff_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), quote_date DATE, payoff_amount NUMERIC(14,2), good_through DATE
);
CREATE TABLE loan.charge_off (
  charge_off_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), charged_off_date DATE, amount NUMERIC(14,2), recovery NUMERIC(14,2)
);
CREATE TABLE loan.repossession (
  repossession_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), repo_date DATE, sale_amount NUMERIC(14,2), deficiency NUMERIC(14,2)
);
CREATE TABLE loan.insurance_policy (
  insurance_policy_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), carrier TEXT, policy_no TEXT, premium NUMERIC(10,2), expires DATE
);
CREATE TABLE loan.gap_coverage (
  gap_coverage_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), provider TEXT, cost NUMERIC(10,2), active BOOLEAN DEFAULT true
);
CREATE TABLE loan.ach_mandate (
  ach_mandate_id BIGSERIAL PRIMARY KEY,
  borrower_id BIGINT REFERENCES loan.borrower(borrower_id), bank_token TEXT, status TEXT, created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE loan.statement (
  statement_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), period_start DATE, period_end DATE, amount_due NUMERIC(12,2)
);
CREATE TABLE loan.dispute (
  dispute_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), opened_date DATE, category TEXT, status TEXT, resolved_date DATE
);
