-- 75_extra.sql — extra operational tables (generated by schemagen)
CREATE TABLE loan.notification (
  notification_id BIGSERIAL PRIMARY KEY,
  user_id BIGINT, channel TEXT, body TEXT, sent_at TIMESTAMPTZ, read_at TIMESTAMPTZ
);
CREATE TABLE loan.communication_log (
  communication_log_id BIGSERIAL PRIMARY KEY,
  borrower_id BIGINT REFERENCES loan.borrower(borrower_id), direction TEXT, medium TEXT, summary TEXT, at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE loan.task (
  task_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), title TEXT, assignee TEXT, status TEXT, due_date DATE
);
CREATE TABLE loan.queue_assignment (
  queue_assignment_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), queue TEXT, assigned_to TEXT, assigned_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE loan.sla_event (
  sla_event_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), sla TEXT, breached BOOLEAN, at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE loan.fraud_flag (
  fraud_flag_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), rule TEXT, severity TEXT, cleared BOOLEAN DEFAULT false
);
CREATE TABLE loan.kyc_check (
  kyc_check_id BIGSERIAL PRIMARY KEY,
  party_id BIGINT REFERENCES loan.party(party_id), provider TEXT, result TEXT, checked_at TIMESTAMPTZ
);
CREATE TABLE loan.aml_screening (
  aml_screening_id BIGSERIAL PRIMARY KEY,
  party_id BIGINT REFERENCES loan.party(party_id), list_name TEXT, hit BOOLEAN, screened_at TIMESTAMPTZ
);
CREATE TABLE loan.consent (
  consent_id BIGSERIAL PRIMARY KEY,
  party_id BIGINT REFERENCES loan.party(party_id), consent_type TEXT, granted BOOLEAN, at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE loan.disclosure (
  disclosure_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), kind TEXT, delivered_at TIMESTAMPTZ
);
CREATE TABLE loan.e_sign_event (
  e_sign_event_id BIGSERIAL PRIMARY KEY,
  document_id BIGINT REFERENCES doc.document(document_id), signer TEXT, signed_at TIMESTAMPTZ, ip INET
);
CREATE TABLE loan.adverse_action_notice (
  adverse_action_notice_id BIGSERIAL PRIMARY KEY,
  decision_id BIGINT REFERENCES loan.underwriting_decision(decision_id), reason_code TEXT REFERENCES ref.decision_reason(code), sent_at TIMESTAMPTZ
);
CREATE TABLE loan.pricing_exception (
  pricing_exception_id BIGSERIAL PRIMARY KEY,
  application_id BIGINT REFERENCES loan.loan_application(application_id), requested_apr NUMERIC(6,3), approved_apr NUMERIC(6,3), approver TEXT
);
CREATE TABLE loan.dealer (
  dealer_id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL, region_id INT REFERENCES ref.region(region_id), rating TEXT
);
CREATE TABLE loan.dealer_contract (
  dealer_contract_id BIGSERIAL PRIMARY KEY,
  dealer_id BIGINT REFERENCES loan.dealer(dealer_id), start_date DATE, end_date DATE, reserve_pct NUMERIC(5,2)
);
CREATE TABLE loan.funding_event (
  funding_event_id BIGSERIAL PRIMARY KEY,
  loan_id BIGINT REFERENCES loan.loan(loan_id), funded_at TIMESTAMPTZ, amount NUMERIC(14,2), method TEXT
);
CREATE TABLE loan.title_record (
  title_record_id BIGSERIAL PRIMARY KEY,
  vehicle_id BIGINT REFERENCES loan.vehicle(vehicle_id), state TEXT, title_no TEXT, status TEXT
);
CREATE TABLE loan.lien (
  lien_id BIGSERIAL PRIMARY KEY,
  vehicle_id BIGINT REFERENCES loan.vehicle(vehicle_id), holder TEXT, perfected_date DATE, released BOOLEAN DEFAULT false
);
CREATE TABLE loan.gps_device (
  gps_device_id BIGSERIAL PRIMARY KEY,
  vehicle_id BIGINT REFERENCES loan.vehicle(vehicle_id), serial_no TEXT, installed_at TIMESTAMPTZ, active BOOLEAN DEFAULT true
);
CREATE TABLE loan.telematics_reading (
  telematics_reading_id BIGSERIAL PRIMARY KEY,
  gps_device_id BIGINT REFERENCES loan.gps_device(gps_device_id), read_at TIMESTAMPTZ, lat NUMERIC(9,6), lon NUMERIC(9,6), odometer INT
);
